package corp.khin.solutions.booqi.domain.model

import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalTime

/**
 * A specific bookable unit of time for a Provider (docs/DOMAIN.md). Value object — equality by
 * value (`providerId` + [date] + [start]), no identity of its own. The slot's length is not part
 * of it: it is the duration of the `Service` being booked, which `Booking` snapshots.
 *
 * Generated by [corp.khin.solutions.booqi.domain.usecase.GenerarTimeSlotsUseCase]. A generated
 * slot means "available per the Provider's Availability" only; whether another `Booking` already
 * occupies it is decided by
 * [corp.khin.solutions.booqi.domain.usecase.ObtenerTimeSlotsDisponiblesUseCase], which is what a
 * Customer-facing flow should use. A `Booking` holds its slot as `Booking.timeSlot`.
 */
data class TimeSlot(
    val providerId: String,
    val date: LocalDate,
    val start: LocalTime,
)
